### ISSUE TITLE
Regex problem with spaces and specific character

### ISSUE THREAD

**Issue by Galiorn** [limalayla/PadID_Humanitaire#9]
-I can't create a camp with a space in it's name like "Iut Amiens"
-We can't put any accents in a camp's name like "Marià" or "ñinos"
-We can write specific character like "& # 1234567890" in the textbox "Location"

**Comment by limalayla** [comment]
Some regex patterns aren't supported in qt, i kind of gave up, spaces will be allowed, but no specific utf8 accents
